// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjHjO4JCfi2-HM3KSju4aGVO47f2oRwpk',
    appId: '1:654248867512:web:f1492eb00d065f3688e64d',
    messagingSenderId: '654248867512',
    projectId: 'ink-and-3cho',
    authDomain: 'ink-and-3cho.firebaseapp.com',
    storageBucket: 'ink-and-3cho.firebasestorage.app',
    measurementId: 'G-LYSP7S6PD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMIR68DqFgj5tVu-me3j_BUeO5mwKkxFk',
    appId: '1:654248867512:android:e8800379f3ae127e88e64d',
    messagingSenderId: '654248867512',
    projectId: 'ink-and-3cho',
    storageBucket: 'ink-and-3cho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY95V2MSA9ahWtehKCmTw1c5o9Ul0r_0A',
    appId: '1:654248867512:ios:a05a7e3a4279f41288e64d',
    messagingSenderId: '654248867512',
    projectId: 'ink-and-3cho',
    storageBucket: 'ink-and-3cho.firebasestorage.app',
    iosBundleId: 'com.example.inkandecho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY95V2MSA9ahWtehKCmTw1c5o9Ul0r_0A',
    appId: '1:654248867512:ios:a05a7e3a4279f41288e64d',
    messagingSenderId: '654248867512',
    projectId: 'ink-and-3cho',
    storageBucket: 'ink-and-3cho.firebasestorage.app',
    iosBundleId: 'com.example.inkandecho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjHjO4JCfi2-HM3KSju4aGVO47f2oRwpk',
    appId: '1:654248867512:web:f703069d47134eec88e64d',
    messagingSenderId: '654248867512',
    projectId: 'ink-and-3cho',
    authDomain: 'ink-and-3cho.firebaseapp.com',
    storageBucket: 'ink-and-3cho.firebasestorage.app',
    measurementId: 'G-W6LCN0772Y',
  );
}
